rails/articles/config/routes.rb
Articles::Application.routes.draw do
  resources :articles
  root :to => 'articles#index'
end

rails/articles/app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :author, :body, :category, :hero_image_url, 
    :optional_image_url, :publication, :title

  belongs_to :category
  belongs_to :author

  default_scope { published_till_today }

  def self.published_till_today
  	where("publication <= (?)", Date.today)
  end

  def self.featured
  	order("RAND()").first
  end

  def self.non_featured(featured_article_id)
  	skip_articles([featured_article_id])
  end

  def self.next_reads(ids)
  	skip_articles(ids).limit(4)
  end

  def self.skip_articles(skipped_ids)
  	where("id NOT IN (?)", skipped_ids)
  end
end

rails/articles/app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :first_name, :last_name

  has_many :articles

  def to_s
  	[first_name, last_name].compact.join(' ')
  end
end

rails/articles/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :articles

  validates :name, presence: { message: 'Please enter the name of category.' }
end

rails/articles/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails/articles/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  	@featured     = Article.featured
  	@article_list = Article.non_featured(@featured.id).limit(3)
  	@next_reads   = Article.next_reads([@featured.id, @article_list.pluck(:id)].flatten)
  end

  def show
  	@article = Article.where(id: params[:id]).first
  	@next_reads  = Article.next_reads([@article.id])
  end
end

rails/articles/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/articles/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails/articles/app/views/articles/index.html.haml
.featured
  =render 'shared/detailed_view_top', article: @featured
  .body_content
    =@featured.body
.article_list
  - @article_list.each do |article|
    .article_list_view
      %h3=article.title
      .body_text
        =truncate(article.body, length: 200, omission: '... (continued)')
      =link_to 'Read More', article_path(article)

rails/articles/app/views/articles/show.html.haml
.detailed_view
  =render 'shared/detailed_view_top', article: @article
  .article_body
    .body_content
      =@article.body
    .small_image_preview

rails/articles/app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{ name: 'keywords', content: 'articles, gale' } 
    %meta{ name: 'description', content: 'An exercise on articles.' }
    %meta{charset: "utf-8"}
      %title
        Articles
      = stylesheet_link_tag 'application'
      = javascript_include_tag 'application'
    = csrf_meta_tag
%body
  #wrapper
    = render 'shared/navigation_links'
    .content-wrapper
      .detail_view
        = yield
      = render 'shared/next_reads'

rails/articles/app/views/shared/_detailed_view_top.html.haml
.small_description
  %h1=article.title
  .date_and_author
    %span.author_name
      =article.author
    |
    %span.publication
      =article.publication.stamp("Thursday, September 14th 2015")
  .featured_image
    =image_tag 'http://placehold.it/900x350'

rails/articles/app/views/shared/_navigation_links.html.haml
.navigation_view
  = link_to 'Home', "/"
  %br
  = link_to 'Nav1', "/"
  %br
  = link_to 'Nav2', '/'
  %br
  = link_to 'Nav3', '/'

rails/articles/app/views/shared/_next_reads.html.haml
.next_reads
  %h2.sub_title What to read next
  - @next_reads.each do |next_read|
    = link_to article_path(next_read) do
      .article_view_small
        .preview_image
          =image_tag 'http://placehold.it/200x150'
        .title
          =next_read.title