django/articles/articles/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls)
]

django/articles/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<article_id>[0-9]+)/$', views.detail, name='detail')
]

django/articles/blog/models.py
from __future__ import unicode_literals

from django.db import models

class Author(models.Model):
    first_name  = models.CharField(max_length=100)
    last_name   = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Article(models.Model):
    title              = models.CharField(max_length=300)
    publication        = models.DateField('date published')
    body               = models.TextField
    hero_image_url     = models.CharField(max_length=300)
    optional_image_url = models.CharField(max_length=300)
    author             = models.ForeignKey(Author, on_delete=models.CASCADE)
    category           = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return (self.title[:75] + '..') if len(self.title) > 75 else self.title

django/articles/blog/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render

from .models import Article

def index(request):
    article_list = Article.objects.order_by('-publication')[:3]
    context = { 'article_list': article_list }
    return render(request, 'blog/index.html', context)

def detail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    return render(request, 'blog/detail.html', {'article': article})

django/articles/blog/templates/blog/detail.html
<div class="detail_view">
<div class="detailed_view">
  <div class="small_description">
    <h1>{{ article.title }}</h1>
    <div class="date_and_author">
      <span class="author_name">
        {{ article.author }}
      </span>
      |
      <span class="publication">
        {{ article.publication }}
      </span>
    </div>
    <div class="featured_image">
      <img alt="900x350" src="http://placehold.it/900x350">
    </div>
  </div>
  <div class="article_body">
    <div class="body_content">
    </div>
    <div class="small_image_preview"></div>
  </div>
</div>
</div>

django/articles/blog/templates/blog/index.html
{% if article_list %}
    <div class="article_list">
    {% for article in article_list %}
      <div class="article_list_view">
	    <h3>{{ article.title }}</h3>
	    <div class="body_text">
	    </div>
	    <a href="{% url 'blog:detail' article.id %}">Read More</a>
	  </div>
    {% endfor %}
    </div>
{% else %}
    <p>No articles are available.</p>
{% endif %}

django/articles/blog/templates/index.html
{% if article_list %}
    <ul>
    {% for article in article_list %}
        <li><a href="/blog/{{ article.id }}/">{{ article.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No articles are available.</p>
{% endif %}